---
title: "Matching and subclassification"
date:
always_allow_html: yes
output:
  github_document:
    toc: true
    toc_depth: 2
editor_options: 
  chunk_output_type: console
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, echo = F, message = F}
knitr::opts_chunk$set(
  cache = T,
  cache.path = '../cache/',
  fig.path = '../fig/',
  message = F,
  warning = F
  )
load_tidy()
library(hrbrthemes)
library(mixtape)
library(stargazer)
```

## Subclassification exercise: Titanic dataset

```{r titanic}

# get the data
dat <- titanic

# sdo
mean(dat$survived[dat$class == 1]) - mean(dat$survived[dat$class != 1])

# define strata
dat %<>%
  mutate(
    st = case_when(
      sex == 0 & age == 1 ~ 'male child',
      sex == 0 & age == 0 ~ 'male adult',
      sex == 1 & age == 1 ~ 'female child',
      sex == 1 & age == 0 ~ 'female adult'
    )
  )

# male children
m_ch_1 <- mean(dat$survived[dat$st == 'male child' & dat$class == 1])
m_ch_0 <- mean(dat$survived[dat$st == 'male child' & dat$class != 1])
diff1 <- m_ch_1 - m_ch_0

# male adults
m_ad_1 <- mean(dat$survived[dat$st == 'male adult' & dat$class == 1])
m_ad_0 <- mean(dat$survived[dat$st == 'male adult' & dat$class != 1])
diff2 <- m_ad_1 - m_ad_0

# female children
f_ch_1 <- mean(dat$survived[dat$st == 'female child' & dat$class == 1])
f_ch_0 <- mean(dat$survived[dat$st == 'female child' & dat$class != 1])
diff3 <- f_ch_1 - f_ch_0

# female adults
f_ad_1 <- mean(dat$survived[dat$st == 'female adult' & dat$class == 1])
f_ad_0 <- mean(dat$survived[dat$st == 'female adult' & dat$class != 1])
diff4 <- f_ad_1 - f_ad_0

# non-first class weights
non_first <- table(dat$st[dat$class != 1])
m_ch_wt <- non_first['male child'] / sum(non_first)
m_ad_wt <- non_first['male adult'] / sum(non_first)
f_ch_wt <- non_first['female child'] / sum(non_first)
f_ad_wt <- non_first['female adult'] / sum(non_first)

# weighted effect
diff1 * m_ch_wt + diff2 * m_ad_wt + diff3 * f_ch_wt + diff4 * f_ad_wt
```

## Exact matching

```{r match}

# get the data
dat <- read_csv('training_example.csv')

# figure 15
ggplot(dat) +
  geom_histogram(aes(x = age), binwidth = 2) +
  facet_wrap(~trainee)

# matching
mat <- dat %>%
  filter(trainee == 0) %>%
  group_by(age) %>%
  summarise(
    earnings = mean(earnings),
    unit = str_c(unit, collapse = ', ')
  )
dat %<>% left_join(mat, by = 'age')

# att
mean(dat$earnings.x[dat$trainee == 1]) - mean(dat$earnings.y[dat$trainee == 1])
```

## Bias correction

```{r bias}

# construct the data
dat <- tribble(
  ~unit, ~y, ~y1, ~y0, ~D, ~X,
  1, 05, 05, NA, 01, 11,
  2, 02, 02, NA, 01, 07,
  3, 10, 10, NA, 01, 05,
  4, 06, 06, NA, 01, 03,
  5, 04, NA, 04, 00, 10,
  6, 00, NA, 00, 00, 08,
  7, 05, NA, 05, 00, 04,
  8, 01, NA, 01, 00, 01
  )

# matching
dat$y0[1:4] <- dat$y0[5:8]

# att (biased)
mean(dat$y1[dat$D == 1] - dat$y0[dat$D == 1])

# bias correction using OLS
reg <- lm(y ~ X, data = dat)
dat$fit_actual <- NA
dat$fit_match <- NA
dat$fit_actual[1:4] <- predict(reg, newdata = filter(dat, D == 1))
dat$fit_match[1:4] <- predict(reg, newdata = filter(dat, D == 0))

# att (corrected)
mean(dat$y1[dat$D == 1] - dat$y0[dat$D == 1] - 
       dat$fit_actual[dat$D == 1] + dat$fit_match[dat$D == 1])
```

## Dehejia and Wahba (2002)

```{r propensity}

# get the data
dat <- nsw_dw
names(dat)[c(4, 6, 7)] <- c('education', 'hispanic', 'married')
dat %<>% filter(data_id == 'Dehejia-Wahba Sample')

# ate (use controls from lalonde_1986)
ate <- mean(dat$re78[dat$treat == 1]) - 
  mean(lalonde_1986$re78[lalonde_1986$treat == 0])

# add cps controls
dat <- plyr::rbind.fill(dat, cps_controls)
dat %<>%
  mutate(
    u74 = ifelse(re74 == 0, 1, 0),
    u75 = ifelse(re75 == 0, 1, 0)
  )

# propensity score
pse <- as.formula('treat ~ 
  age + I(age ^ 2) + I(age ^ 3) + 
  education + I(education ^ 2) +
  married + nodegree + black + hispanic + re74 + re75 + u74 + u75 +
  education * re74 + hispanic * u74'
  )
psm <- glm(pse, family = binomial(link = 'logit'), data = dat)
dat$score <- predict(psm, type = 'response')

# figure 23
ggplot(dat) +
  geom_histogram(aes(x = score, y = ..density..)) +
  facet_wrap(~treat)

# match (using arm::matching)
mat <- arm::matching(z = dat$treat, score = dat$score)
mat <- dat[mat$matched, ]
arm::balance(dat, mat, psm)

# ate
mean(mat$re78[mat$treat == 1] - mat$re78[mat$treat == 0])
```

## Coarsened exact matching

```{r coarse}

# load cem package
library(cem)

# age cutpoints
agecut <- c(0, 10, 20, 30, 40, 60)

# variables to drop
drops <- names(dat)[c(1:2, 11, 14:15, 19)]

# implement: not working
# mat <- cem(
#   treatment = 'treat',
#   data = na.omit(dat),
#   drop = drops,
#   cutpoints = list(age = agecut)
#   )
```
