---
title: "Potential outcomes causal model"
date:
always_allow_html: yes
output:
  md_document:
    toc: true
    toc_depth: 2
editor_options: 
  chunk_output_type: console
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, echo = F, message = F}
knitr::opts_chunk$set(
  cache = T,
  cache.path = '../cache/',
  fig.path = '../fig/',
  message = F,
  warning = F
  )
load_tidy()
library(mixtape)
```

## Yule (1899)

```{r yule}

# get the data
dat <- yule

# reshape yule to long
pat <- '(^[A-z]+[65]*)(\\d{2,4})(_\\d|O|I)*'
dat %<>% gather(variable, value, -1:-7)
dat %<>% mutate(
  series = str_replace(dat$variable, pat, '\\1\\3'),
  year = str_replace(dat$variable, pat, '\\2')
  ) %>%
  filter(!year %in% c('7181', '8191')) %>%
  select(-variable)

# fix two digit years
dat %<>% within({
  year[year %in% str_c(7:9, 1)] <- str_c(18, year[year %in% str_c(7:9, 1)])
  })

# reshape yule to wide (panel data)
dat %<>% spread(series, value, c(-1:-7, -10), fill = NA)

# prefer Popn_2 for population changes
dat %<>% mutate(
  Popn_2 = ifelse(is.na(Popn_2), Popn, Popn_2)
  )

# calculate out/old ratios
dat %<>% mutate(
  outratio = (ChABO + ChNotABO + FABO + FNotABO + MABO + MNotABO) / 
    (ChABI + ChNotABI + FABI + FNotABI + MABI + MNotABI),
  oldratio = (F65 + M65) / Popn_2,
  outratio = ifelse(outratio == Inf, NA, outratio),
  oldratio = ifelse(oldratio == Inf, NA, oldratio)
  )

# calculate decadal changes
dat %<>%
  group_by_at(1:7) %>%
  mutate(
    dpop  = Popn_2 / lag(Popn_2, order_by = year) * 100,
    dold  = oldratio / lag(oldratio, order_by = year) * 100,
    dout  = outratio / lag(outratio, order_by = year) * 100,
    dpaup = pauper / lag(pauper, order_by = year) * 100
  )

# impute dpop (= 0) if only missing 1891
IDs <- dat %>%
  group_by(ID) %>%
  summarise(na = sum(is.na(Popn_2))) %>%
  filter(na == 2) %>%
  use_series('ID')
dat %<>% mutate(
  dpop  = ifelse(is.na(dpop) & year == 1891 & !ID %in% IDs, 0, dpop)
  )

# adjust if change in paupers == Inf
dat %<>% mutate(
  dpaup = ifelse(dpaup == Inf, NA, dpaup)
  )

# model of poverty and public assistance
reg <- lm(dpaup ~ dout + dold + dpop, data = filter(dat, Type > 1))

# table 10
stargazer(reg)
```
<br>

## Simple difference in means decomposition

```{r diff_means}

# construct the data
dat <- tribble(
  ~patient, ~y1, ~y0,
  1, 7, 1,
  2, 5, 6,
  3, 5, 1,
  4, 7, 8,
  5, 4, 2,
  6, 10, 1,
  7, 1, 10,
  8, 5, 6,
  9, 3, 7,
  10, 9, 8
)
dat %<>% mutate(delta = y1 - y0)

# gap function
gap <- function(data) {
  tmp <- sample(1:10, 5, replace = F)
  mean(data$y1[1:10 %in% tmp]) - mean(data$y0[!1:10 %in% tmp])
}

# simulate
sdo <- replicate(1E4, gap(dat)) ; skim(sdo)
```

## STAR Experiment

```{r star_fig08, results = 'asis'}

library(lfe)

# get the data
dat <- star_sw

# models
mod <- 'tscorek ~ sck + rak' %>%
  list(
    .,
    str_c(., ' | schidkn'),
    str_c(., ' + white + boy + freelunk | schidkn'),
    str_c(., ' + freelunk + totexpk | schidkn')
  )

# regressions
reg <- map(mod, ~felm(as.formula(.), data = dat))

# figure 8
stargazer::stargazer(reg, type = 'html')
```
<br>

```{r star_fig11}

# first graders by class
fir <- rep('Regular', nrow(dat))
fir[is.na(dat$sc1) & is.na(dat$ra1)] <- NA
fir[dat$sc1 == 1] <- 'Small'
fir[dat$ra1 == 1] <- 'Aide'

# second graders by class
sec <- rep('Regular', nrow(dat))
sec[is.na(dat$sc2) & is.na(dat$ra2)] <- NA
sec[dat$sc2 == 1] <- 'Small'
sec[dat$ra2 == 1] <- 'Aide'

# figure 11
table(fir, sec)
```
