---
title: "Directed acyclical graphs"
date:
always_allow_html: yes
output:
  md_document:
    toc: true
    toc_depth: 2
editor_options: 
  chunk_output_type: console
---

```{r setup, echo = F, message = F}
knitr::opts_chunk$set(
  cache = T,
  cache.path = '../cache/',
  fig.path = '../fig/',
  message = F,
  warning = F
  )
load_tidy()
library(mixtape)
```

## Gender disparities controlling for occupation

```{r gender}

library(ggraph)
library(tidygraph)

# network
net <- tribble(
  ~from, ~to,
  'A', 'o',
  'A', 'y', 
  'F', 'd',
  'F', 'o',
  'd', 'o',
  'o', 'y',
  )
net %<>% as_tbl_graph(directed = T)
net %<>% 
  activate(edges) %>%
  mutate(
    lty  = c('u', 'u', 'o', 'u', 'o', 'o')
    )

# dag
ggraph(net, layout = 'kk') +
  geom_edge_link(
    aes(linetype = lty),
    arrow = arrow(length = unit(2, "mm")),
    start_cap = circle(3, "mm"), end_cap = circle(3, "mm")
  ) + 
  geom_node_point() +
  geom_node_text(
    aes(label = name), hjust = -1, vjust = 2
  ) +
  theme_void() +
  theme(legend.position = 'none')


# construct the data
set.seed(8)
dat <- tibble(
  female = as.numeric(runif(1E4, 0, 1) >= 0.5),
  ability = rnorm(1E4, 0, 1)
  )

# outcomes
#   discrim = all females experience discrimination
#   occupat = f(ability, discrimination) (no discrim <=> M/F sort the same)
#   wage = g(ability, discrimination, occupation)
dat %<>% mutate(
  discrim = female,
  occupat = 1 + 2 * ability + 0 * female - 2 * discrim + rnorm(1E4, 0, 1),
  wage = 1 + 2 * ability - 1 * discrim + 1 * occupat + rnorm(1E4, 0, 1)
  )

# regressions
#   unconditional effect of discrimination: wage (direct) + occupat (indirect)
#   adding occupation controls for collider!: female -> occupat <- ability
#   correct specification
reg <- list(
  lm(wage ~ discrim, data = dat),
  lm(wage ~ discrim + occupat, data = dat),
  lm(wage ~ discrim + occupat + ability, data = dat)
  )

# tidy the data
reg %<>% map_dfr(tidy)
reg$model <- c(
  rep('Biased unconditional', 2),
  rep('Biased', 3),
  rep('Unbiased conditional', 4)
  )

# table 8
out <- gather(reg, statistic, value, -term, -model) %>%
  filter(statistic %in% c('estimate', 'std.error')) %>%
  mutate(
    value = format(value, digits = 2),
    value = str_trim(value),
    value = if_else(statistic == 'std.error', str_c('(', value, ')'), value)
  ) %>%
  spread(model, value, fill = '') %>%
  select(-statistic)

out <- out[c(1:2, 5:6, 7:8, 3:4), c(1, 3, 2, 4)]
out[, 1] <- c(
  '(Intercept)', '',
  'Female', '',
  'Occupation', '',
  'Ability', ''
)
names(out)[1] <- c('Covariates:')
out %<>% add_row(
  `Covariates:` = 'N',
  `Biased unconditional` = '10,000',
  `Biased` = '10,000',
  `Unbiased conditional` = '10,000'
  )

knitr::kable(
  out,
  align = 'c',
  row.names = F,
  format = 'html'
  ) %>%
  kableExtra::row_spec(9, bold = T) %>%
  kableExtra::kable_styling()
```

## Qualitative change in sign

```{r qual_change}

library(sandwich)
library(lmtest)

set.seed(541)

# dag properties
#   Z -> D -> Y
#   D -> X <- Y

# construct the data 
dat <- tibble(
  z = rnorm(2500, 0, 1),
  k = rnorm(2500, 10, 4),
  d = 0
  )
dat$d[dat$k >= 12] <- 1

# add x and y
dat %<>% mutate(
  y = 50 * d + 100 + rnorm(2500, 0, 1),
  x = 50 * d + y + rnorm(2500, 50, 1)
  )

# regressions
reg <- list(
  lm(y ~ d, data = dat),
  lm(y ~ x, data = dat),
  lm(y ~ d + x, data = dat)
  )

# use stata style robust standard errors
reg <- map(reg, ~coeftest(.x, vcov = vcovHC(.x, "HC1")))

# tidy the data
reg %<>% map_dfr(tidy)
reg$model <- c(
  rep(1, 2),
  rep(2, 2),
  rep(3, 3)
  )

# table 9
out <- gather(reg, statistic, value, -term, -model) %>%
  filter(statistic %in% c('estimate', 'std.error')) %>%
  mutate(
    value = format(value, digits = 2),
    value = str_trim(value),
    value = if_else(statistic == 'std.error', str_c('(', value, ')'), value)
  ) %>%
  spread(model, value, fill = '') %>%
  select(-statistic)

out$term <- c(
  '(Intercept)', '',
  'd', '',
  'x', ''
)
names(out)[1] <- c('Covariates:')
out %<>% add_row(
  `Covariates:` = 'N',
  `1` = '2,500',
  `2` = '2,500',
  `3` = '2,500'
  )

knitr::kable(
  out,
  align = 'c',
  row.names = F,
  format = 'html'
  ) %>%
  kableExtra::row_spec(7, bold = T) %>%
  kableExtra::kable_styling()
```
<br>

## Nonrandom sample selection

```{r nonrandom}

set.seed(3444)

# construct the data
dat <- tibble(
  beauty = rnorm(2500, 0, 1),
  talent = rnorm(2500, 0, 1),
  score  = beauty + talent
  )

# add collider variable: star
c85 <- quantile(dat$score, probs = 0.85)
dat %<>% mutate(
  star = score > c85
  )

# figure 7
ggplot(dat) +
  geom_point(aes(talent, beauty, shape = star)) +
  geom_abline(
    intercept = c85,
    slope = -1,
    col = 'red'
  ) +
  scale_shape_manual(name = 'Star?', values = c(1, 16)) +
  labs(x = 'Talent', y = 'Beauty', title = 'Aspiring actors and actresses') +
  ggthemes::theme_tufte()
```
