---
title: "Regression discontinuity"
date:
always_allow_html: yes
output:
  github_document:
    toc: true
    toc_depth: 2
editor_options: 
  chunk_output_type: console
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, echo = F, message = F}
knitr::opts_chunk$set(
  cache = T,
  cache.path = '../cache/',
  fig.path = '../fig/',
  message = F,
  warning = F
  )
load_tidy()
library(hrbrthemes)
library(mixtape)
library(stargazer)
```

## Definition

```{r simulation}

set.seed(1234567)

# simulate the data
dat <- tibble(
  x = rnorm(1000, 50, 25)
  ) %>%
  mutate(
    x = if_else(x < 0, 0, x)
  ) %>%
  filter(x < 100)
skim(dat)

# cutoff at x = 50
dat %<>%
  mutate(
    D  = if_else(x > 50, 1, 0),
    y1 = 25 + 0 * D + 1.5 * x + rnorm(n(), 0, 20)
  )

# figure 35
ggplot(aes(x, y1, colour = factor(D)), data = dat) +
  geom_point(alpha = 0.5) +
  geom_vline(xintercept = 50, colour = "grey", linetype = 2) +
  stat_smooth(method = "lm", se = F) +
  scale_colour_ipsum(name = "Treatment") +
  labs(x = "Test score (X)", y = "Potential Outcome (Y1)") +
  theme_ipsum()

# simulate the discontinuity
dat %<>%
  mutate(
    y2 = 25 + 40 * D + 1.5 * x + rnorm(n(), 0, 20)
  )

# figure 36
ggplot(aes(x, y2, colour = factor(D)), data = dat) +
  geom_point(alpha = 0.5) +
  geom_vline(xintercept = 50, colour = "grey", linetype = 2) +
  stat_smooth(method = "lm", se = F) +
  scale_colour_ipsum(name = "Treatment") +
  labs(x = "Test score (X)", y = "Potential Outcome (Y)") +
  theme_ipsum()

# simultate nonlinearity
dat %<>%
  mutate(
    y3 = 25 + 0 * D + 2 * x + x ^ 2 + rnorm(n(), 0, 20)
  )

# figure 36
ggplot(aes(x, y3, colour = factor(D)), data = dat) +
  geom_point(alpha = 0.5) +
  geom_vline(xintercept = 50, colour = "grey", linetype = 2) +
  scale_colour_ipsum(name = "Treatment") +
  labs(x = "Test score (X)", y = "Potential Outcome (Y)") +
  theme_ipsum()

```


